bcmdhd: use default_groups in debug_dpc_bounds kobj_type
dhd_linux_exportfs.c:2997:3: error: field designator 'default_attrs' does not
refer to any field in type 'struct kobj_type'
        .default_attrs = debug_dpc_bounds_attrs,
         ^
1 error generated.

Bug: 229037569
Signed-off-by: Will McVicker <willmcvicker@google.com>
Change-Id: Ie41be84e81d4b1b9d1083f2cafab976808021dc3
(cherry picked from commit 18b070e6c7ed3721b5038b53add66f9c6389cf8d)