bcmdhd: fix _S() macro redefinition
Rename local stringify macros definitions which collide with ctype.h
header file. This fixes the following type of errors:

  wlan/bcmdhd4389/wl_cfg80211.c:1404:9:
  error: '_S' macro redefined [-Werror,-Wmacro-redefined]
  #define _S(x) #x
          ^
  common/include/linux/ctype.h:17:9: note: previous definition is here
  #define _S      0x20    /* white space (space/lf/tab) */
          ^

Bug: 215712060
Signed-off-by: Carlos Llamas <cmllamas@google.com>
Change-Id: Ibaee2be45c25ac81bf9350aecea1dff8caeb7735
(cherry picked from commit 43493f5c7cce0d6807c78780bece6ebb122f230d)